# -*- coding: utf-8 -*-
"""NLP Sentiment Pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZV6DP9VTDVIKUlGcBBen0Gkti7gyVC_i
"""

!pip install transformers datasets scikit-learn pandas numpy matplotlib seaborn plotly streamlit mlflow -q
!pip install torch --upgrade -q

# Fix the VideoReader bug directly
import sys
sys.modules.pop('torchvision', None)

import os
os.environ['DISABLE_TORCHVISION'] = '1'

print("✓ All libraries installed")

# After CELL 01 finishes — go to Runtime → Restart session → Yes
# Then start from CELL 03 below
print("Please restart runtime now — Runtime → Restart session → Yes")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings, pickle, json, re
warnings.filterwarnings('ignore')

from sklearn.model_selection import train_test_split
from sklearn.metrics import (classification_report, confusion_matrix,
                              ConfusionMatrixDisplay, roc_auc_score, roc_curve)
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer
from transformers import pipeline as hf_pipeline
import torch

plt.rcParams['figure.figsize'] = (10, 5)
plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.right'] = False
print("✓ All imports done")

from datasets import load_dataset

print("Loading IMDB dataset...")
dataset  = load_dataset("stanfordnlp/imdb")
train_df = pd.DataFrame(dataset['train'])
test_df  = pd.DataFrame(dataset['test'])

print("✓ Dataset loaded!")
print(f"Train size: {len(train_df)}")
print(f"Test size:  {len(test_df)}")
print(f"Columns: {train_df.columns.tolist()}")
print(f"\nSample:\n{train_df['text'].iloc[0][:200]}")

fig, axes = plt.subplots(1, 2, figsize=(12, 5))

train_df['label'].value_counts().plot(kind='bar', ax=axes[0],
    color=['#D85A30','#378ADD'], width=0.4)
axes[0].set_title('Sentiment Distribution', fontsize=13, fontweight='bold')
axes[0].set_xticklabels(['Negative','Positive'], rotation=0)
axes[0].set_ylabel('Count')

train_df['length'] = train_df['text'].apply(len)
axes[1].hist(train_df[train_df['label']==0]['length'],
             bins=50, alpha=0.6, color='#D85A30', label='Negative')
axes[1].hist(train_df[train_df['label']==1]['length'],
             bins=50, alpha=0.6, color='#378ADD', label='Positive')
axes[1].set_title('Review Length by Sentiment', fontsize=13, fontweight='bold')
axes[1].set_xlabel('Review Length (characters)')
axes[1].set_ylabel('Count')
axes[1].legend()

plt.tight_layout()
plt.show()
print("INSIGHT: Dataset perfectly balanced — 25,000 positive and 25,000 negative.")

def clean_text(text):
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = text.lower().strip()
    text = re.sub(r'\s+', ' ', text)
    return text

print("Cleaning text...")
train_df['clean_text'] = train_df['text'].apply(clean_text)
test_df['clean_text']  = test_df['text'].apply(clean_text)

train_small = train_df.sample(5000, random_state=42).reset_index(drop=True)
test_small  = test_df.sample(1000, random_state=42).reset_index(drop=True)

print(f"✓ Text cleaned")
print(f"Train subset: {len(train_small)} | Test subset: {len(test_small)}")
print(f"\nCleaned sample: {train_small['clean_text'].iloc[0][:150]}")

print("Training baseline TF-IDF + Logistic Regression...")

tfidf = TfidfVectorizer(max_features=10000, ngram_range=(1,2))
X_train_tfidf = tfidf.fit_transform(train_small['clean_text'])
X_test_tfidf  = tfidf.transform(test_small['clean_text'])

y_train = train_small['label']
y_test  = test_small['label']

lr_model = LogisticRegression(max_iter=1000, random_state=42)
lr_model.fit(X_train_tfidf, y_train)

y_pred = lr_model.predict(X_test_tfidf)
y_prob = lr_model.predict_proba(X_test_tfidf)[:,1]
auc    = roc_auc_score(y_test, y_prob)

print(f"\nBaseline TF-IDF + Logistic Regression")
print(f"AUC-ROC: {auc:.4f}")
print(classification_report(y_test, y_pred,
      target_names=['Negative','Positive']))

pickle.dump(lr_model, open('lr_model.pkl','wb'))
pickle.dump(tfidf, open('tfidf_vectorizer.pkl','wb'))
print("✓ Baseline model saved")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

ConfusionMatrixDisplay.from_predictions(
    y_test, y_pred,
    display_labels=['Negative','Positive'],
    cmap='Blues', ax=axes[0])
axes[0].set_title('Baseline — Confusion Matrix', fontsize=13, fontweight='bold')

fpr, tpr, _ = roc_curve(y_test, y_prob)
axes[1].plot(fpr, tpr, color='#378ADD', linewidth=2,
             label=f'TF-IDF LR (AUC={auc:.3f})')
axes[1].plot([0,1],[0,1],'k--', alpha=0.4, label='Random')
axes[1].set_title('ROC Curve — Baseline', fontsize=13, fontweight='bold')
axes[1].set_xlabel('False Positive Rate')
axes[1].set_ylabel('True Positive Rate')
axes[1].legend()

plt.tight_layout()
plt.show()
print(f"Baseline AUC: {auc:.4f}")

print("Loading pretrained DistilBERT...")
sentiment_pipe = hf_pipeline(
    "sentiment-analysis",
    model="distilbert-base-uncased-finetuned-sst-2-english",
    truncation=True,
    max_length=512
)

texts  = test_small['clean_text'].tolist()[:400]
labels = test_small['label'].tolist()[:400]

all_probs, all_preds = [], []
print("Running predictions...")
for i, text in enumerate(texts):
    result = sentiment_pipe(text[:512])[0]
    prob   = result['score'] if result['label']=='POSITIVE' else 1-result['score']
    pred   = 1 if result['label']=='POSITIVE' else 0
    all_probs.append(prob)
    all_preds.append(pred)
    if i % 50 == 0:
        print(f"Progress: {i}/{len(texts)}")

bert_auc   = roc_auc_score(labels, all_probs)
all_labels = labels

print(f"\n✓ DistilBERT Results")
print(f"AUC-ROC: {bert_auc:.4f}")
print(classification_report(labels, all_preds,
      target_names=['Negative','Positive']))
print(f"Improvement over baseline: +{bert_auc - auc:.4f}")

fig, axes = plt.subplots(1, 2, figsize=(14, 5))

ConfusionMatrixDisplay.from_predictions(
    all_labels, all_preds,
    display_labels=['Negative','Positive'],
    cmap='Blues', ax=axes[0])
axes[0].set_title('DistilBERT — Confusion Matrix', fontsize=13, fontweight='bold')

fpr_bert, tpr_bert, _ = roc_curve(all_labels, all_probs)
axes[1].plot(fpr, tpr, color='#378ADD', linewidth=2,
             label=f'TF-IDF LR (AUC={auc:.3f})')
axes[1].plot(fpr_bert, tpr_bert, color='#D85A30', linewidth=2,
             label=f'DistilBERT (AUC={bert_auc:.3f})')
axes[1].plot([0,1],[0,1],'k--', alpha=0.4, label='Random')
axes[1].set_title('ROC Curves — Model Comparison', fontsize=13, fontweight='bold')
axes[1].set_xlabel('False Positive Rate')
axes[1].set_ylabel('True Positive Rate')
axes[1].legend()

plt.tight_layout()
plt.show()

print(f"Baseline TF-IDF AUC:  {auc:.4f}")
print(f"DistilBERT AUC:       {bert_auc:.4f}")
print(f"Improvement:          +{bert_auc - auc:.4f}")
print("✓ DistilBERT wins!")

test_reviews = [
    "This movie was absolutely amazing! Best film I have ever seen.",
    "Terrible film. Complete waste of time. Very disappointing.",
    "It was okay, nothing special but not bad either.",
    "Outstanding performance by the cast. Highly recommended!",
    "Boring and predictable. I fell asleep halfway through."
]

print("=== LIVE PREDICTIONS ===\n")
for review in test_reviews:
    result = sentiment_pipe(review[:512])[0]
    label  = "POSITIVE " if result['label']=='POSITIVE' else "NEGATIVE "
    score  = result['score']
    print(f"Review:     {review[:60]}")
    print(f"Prediction: {label} ({score*100:.1f}% confidence)")
    print()
print("✓ Pipeline working perfectly")

import mlflow

mlflow.set_experiment("nlp-sentiment-pipeline")

with mlflow.start_run(run_name="DistilBERT_Pretrained"):
    mlflow.log_param("model", "distilbert-base-uncased-finetuned-sst-2-english")
    mlflow.log_param("test_samples", len(labels))
    mlflow.log_metric("roc_auc", bert_auc)
    mlflow.log_metric("baseline_auc", auc)
    mlflow.log_metric("improvement", bert_auc - auc)

with mlflow.start_run(run_name="TFIDF_Baseline"):
    mlflow.log_param("model", "TF-IDF + Logistic Regression")
    mlflow.log_param("max_features", 10000)
    mlflow.log_metric("roc_auc", auc)

print("✓ MLflow tracking complete")

print("\n" + "="*55)
print("  NLP SENTIMENT PIPELINE — COMPLETE")
print("="*55)
print(f"Dataset:        IMDB Reviews (50,000 samples)")
print(f"Task:           Binary Sentiment Classification")
print(f"Baseline AUC:   {auc:.4f} (TF-IDF + Logistic Regression)")
print(f"DistilBERT AUC: {bert_auc:.4f} (Pretrained Transformer)")
print(f"Improvement:    +{bert_auc - auc:.4f}")
print(f"\nFiles saved:")
print(f"  lr_model.pkl         — baseline model")
print(f"  tfidf_vectorizer.pkl — TF-IDF vectorizer")
print(f"\nNext steps:")
print(f"  1. Download lr_model.pkl + tfidf_vectorizer.pkl")
print(f"  2. Create GitHub repo: nlp-sentiment-pipeline")
print(f"  3. Upload files + deploy on Streamlit Cloud")
print("="*55)